@TOTDistribution.WebApi_HostAddress = http://localhost:5124

GET {{TOTDistribution.WebApi_HostAddress}}/totd/obtain
Accept: application/json

###

POST {{TOTDistribution.WebApi_HostAddress}}/totd/get-distribution
Content-Type: application/json

{
    "mapUid": "ssCVidzcPRtF9Wb3_JaDkoXthse",
    "groupUid": "7c6cc4f7-8a72-45cd-a302-fafee2c2e567",
    "authorScore": 48002,
    "goldScore": 51000,
    "silverScore": 58000,
    "bronzeScore": 73000
}