@NadeoRefinery.HostAddress = http://localhost:5124

GET {{NadeoRefinery.HostAddress}}/totd/map-info
Accept: application/json

###

POST {{NadeoRefinery.HostAddress}}/totd/distribution
Content-Type: application/json

{
    "mapUid": "H8fitfXs3a_eGmWjtPvLiNffuT8",
    "groupUid": "40983c5d-8caf-493f-bb9e-4f86516ecf64",
    "authorScore": 46391,
    "goldScore": 50000,
    "silverScore": 56000,
    "bronzeScore": 70000
}