@NadeoRefinery.HostAddress = http://localhost:5124

GET {{NadeoRefinery.HostAddress}}/totd/obtain
Accept: application/json

###

POST {{NadeoRefinery.HostAddress}}/totd/get-distribution
Content-Type: application/json

{
    "mapUid": "LTSmGzmOCnWam4uPnv3Z0E_nPIb",
    "groupUid": "068fbc0d-924e-48f4-9f42-47d9309666eb",
    "authorScore": 50939,
    "goldScore": 54000,
    "silverScore": 62000,
    "bronzeScore": 77000
}