@NadeoRefinery.HostAddress = http://localhost:5124

GET {{NadeoRefinery.HostAddress}}/totd/map-info
Accept: application/json

###

POST {{NadeoRefinery.HostAddress}}/totd/distribution
Content-Type: application/json

{
    "mapUid": "5vkXMrKBAQP24QQrj2OchuxtOZ1",
    "groupUid": "1b432ad8-d83d-4253-87e2-089eb6957188",
    "authorScore": 50502,
    "goldScore": 54000,
    "silverScore": 61000,
    "bronzeScore": 76000
}

###

GET {{NadeoRefinery.HostAddress}}/totd/author-record
Content-Type: application/json

{
    "accountId": "b8df00f6-431c-40f8-96fc-5cd83906c520",
    "mapId" : "6fe651d8-1435-44be-9aa1-0418fa326b17"
}